# Generated by Django 3.0.5 on 2020-04-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axfapp', '0002_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('trackid', models.CharField(max_length=20)),
            ],
        ),
    ]
