# Generated by Django 3.0.5 on 2020-04-29 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axfapp', '0003_nav'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shop',
            new_name='Mustbuy',
        ),
        migrations.AlterModelOptions(
            name='nav',
            options={'ordering': ['trackid']},
        ),
    ]
