# Generated by Django 3.0.5 on 2020-04-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axfapp', '0006_foodtype_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtype',
            name='childtypenames',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='typename',
            field=models.CharField(max_length=200),
        ),
    ]
