# Generated by Django 3.0.5 on 2020-04-30 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axfapp', '0008_auto_20200430_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='isselected',
        ),
    ]
