# Generated by Django 3.0.5 on 2020-04-30 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axfapp', '0009_remove_goods_isselected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='productlongname',
        ),
    ]
