# Generated by Django 3.0.5 on 2020-04-30 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axfapp', '0010_remove_goods_productlongname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodtype',
            options={'ordering': ['id']},
        ),
    ]
