# Generated by Django 3.0.5 on 2020-04-30 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axfapp', '0011_auto_20200430_2128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodtype',
            options={'ordering': ['typesort']},
        ),
    ]
