# Generated by Django 3.0.5 on 2020-05-03 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axfapp', '0012_auto_20200430_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userAccount', models.CharField(max_length=20, unique=True)),
                ('userPasswd', models.CharField(max_length=20)),
                ('userName', models.CharField(max_length=20)),
                ('userPhone', models.CharField(max_length=20)),
                ('userAddress', models.CharField(max_length=200)),
                ('userIcon', models.CharField(max_length=200)),
            ],
        ),
    ]
