# Generated by Django 3.0.5 on 2020-05-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axfapp', '0013_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userRank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='userToken',
            field=models.CharField(default='', max_length=200),
        ),
    ]
