# Generated by Django 3.0.5 on 2020-05-05 22:07

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axfapp', '0014_auto_20200504_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userIcon',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='./axfapp/media/icons'), upload_to=''),
        ),
    ]
