# Generated by Django 3.0.5 on 2020-05-05 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axfapp', '0015_auto_20200506_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userIcon',
            field=models.CharField(max_length=200),
        ),
    ]
