# Generated by Django 3.0.5 on 2020-05-08 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axfapp', '0017_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=20)),
                ('userid', models.CharField(max_length=20)),
                ('progress', models.IntegerField()),
            ],
        ),
    ]
